services:
  pg:
    image: postgres
    container_name: database-dashboard
    restart: always
    environment:
      POSTGRES_NAME: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:5432
